### ISSUE TITLE
Add Images to Plants

### ISSUE THREAD

**Issue by danielBingham** [danielBingham/foresttofarm.org#24]
Add Images to plant boxes on the plant list page and to the plant detail page. 

**Branch**: feature/images
**PR**: #57 
## Acceptance Criteria
- [ ] Should allow uploading of new images from the plant detail page
- [ ] Should display primary associated image on the plant list page
- [ ] Should display primary associated image on the plant detail page 
- [ ] Should allow clicking on the primary image from the plant detail page to reach the plant gallery page 
- [ ] Should display all associated images on the plant gallery page
- [ ] Should allow editing of image from the plant gallery page
## Master TODO
- [x] **Define** scope
- [x] **Design** system to associate images to plants
- [x] **Design** method for uploading images
- [x] **Design** system to handle images for local development (reference production server?)
- [x] **Research** accepting image uploads in a Rails api layer with out using rails form helpers
- [x] **Write** database table (see proposed)
- [x] **Write** `Image` model and add `has_many` relationship to `Plant` model
- [x] **Write** a nested `images` resourceful route with
  - [x] `GET /plants/:plant_id/images/` -> blank site route on the backend, view will be handled on front end
  - [x] `GET /plants/:plant_id/images/new` -> blank site route on the backend, form will be handled by frontend view template 
  - [x] `GET /plants/:plant_id/images/:id/edit` -> blank site route on the backend, editing will be handled on the fronted with JCrop
  - [x] `GET /plants/:plant_id/images/:id` -> blank site route on the backend, on frontend image detail 
    page, view full sized image and attribution
- [x] **Write** a nested `images` api endpoint resourceful route with
  - [x] `GET /api/v0/plants/:plant_id/images` -> `Api::V0::ImageController#index`, return a list of all images for the given plant
  - [x] `GET /api/v0/plants/:plant_id/images/:id` -> `Api::V0::ImageController#show`, return details of the single requested image
  - [x] `POST /api/v0/plants/:plant_id/images` -> `Api::V0::ImageController#create`, perform actual image uploading and put full image in proper location
  - [ ] `PATCH /api/v0/plants/:plant_id/images/:id` -> `Api::V0::ImageController#update`, perform actual image editing on the backend and put cropped image in the proper place
  - [x] `DELETE /api/v0/plants/:plant_id/images/:id` -> `Api::V0::ImageController#destroy`, delete the image from the server and database
- [x] **Write** `ImageService` on the backend to perform actual image handling
  - [x] **Write** `ImageService#handleUpload`
  - [x] **Write** `ImageService#handleCrop`
- [ ] **Add** JCrop library to frontend
- [x] **Write** `PlantImageUploadView` on frontend
  - [x] **Write** `plant-image-upload-template.html.mustache`
- [ ] **Write** `PlantImageCropView` on the frontend
  - [ ] **Write** `plant-image-crop-template.html.mustache`
- [x] **Write** `ImageService` on the frontend to perform actual image handling -- should take a base end point to allow it to be generalized for non-plant images in future
  - [x] **Write** `ImageService.create`
  - [ ] **Write** `ImageService.update`
- [x] **Write** `Image` model on the front end
  - [x] **Write** `Image.getUrl` to generate url from id
- [x] **Select** a spinner gif to use while we're waiting for Deferreds to resolve
- [ ] **Clean Up** Image Upload leftovers.  See https://github.com/danielBingham/foresttofarm.org/issues/24#issuecomment-249734368
- [ ] **Clean Up** Reorganize our javascript and clean up the naming.  It's gotten a little cluttered.

**Comment by danielBingham** [comment]
# Research and Planning

**Branch**: feature/images
**PR**: #57 

**Questions**
- **Scope** What's our scope?
- **Attribution** How are we going to handle attribution?
- **Editing** Is it worthwhile to provide more than just image cropping?  What frontend image editing library should we use?
- **Storage** How are we going to store the images?  Where?  Should we use a CDN?
- **Local Development** How are we going to handle images in local development?
- **Image Uploading** How do we accept image uploads sent from front end to Ruby api?
- **Migration** Should we use a migration or continue hand writing schema?

**TODO**
- Write database table (see proposed)
- Write `Image` model and add `has_many` relationship to `Plant` model
- Write a nested `images` resourceful route with
  - `GET /plants/:plant_id/images/` -> blank site route on the backend, view will be handled on front end
  - `GET /plants/:plant_id/images/new` -> blank site route on the backend, form will be handled by frontend view template 
  - `GET /plants/:plant_id/images/:id/edit` -> blank site route on the backend, editing will be handled on the fronted with JCrop
  - `GET /plants/:plant_id/images/:id` -> blank site route on the backend, on frontend image detail 
    page, view full sized image and attribution
- Write a nested `images` api endpoint resourceful route with
  - `GET /api/v0/plants/:plant_id/images` -> `Api::V0::ImageController#index`, return a list of all images for the given plant
  - `GET /api/v0/plants/:plant_id/images/:id` -> `Api::V0::ImageController#show`, return details of the single requested image
  - `POST /api/v0/plants/:plant_id/images` -> `Api::V0::ImageController#create`, perform actual image uploading and put full image in proper location
  - `PATCH /api/v0/plants/:plant_id/images/:id` -> `Api::V0::ImageController#update`, perform actual image editing on the backend and put cropped image in the proper place
- Write `ImageService` on the backend to perform actual image handling
  - Write `ImageService#handleUpload`
  - Write `ImageService#handleCrop`
- Add JCrop library to frontend
- Write `PlantImageUploadView` on frontend
- Write `PlantImageEditView` on the frontend
- Write `ImageService` on the frontend to perform actual image handling -- should take a base end point to allow it to be generalized for non-plant images in future
  - Write `ImageService.create`
  - Write `ImageService.update`
- Write `Image` model on the front end
  - Write `Image.getUrl` to generate url from id
- Select a spinner gif to use while we're waiting for Deferreds to resolve

**Proposed** database table structure for images:

``` sql
/* Track images that have been uploaded.  They'll be stored by their id
assigned in this table, so that we can always generate a file path from
an id programatically. */
CREATE TABLE `images` (
    `id`  int  NOT NULL AUTO_INCREMENT,
     `plant_id`  int  NOT NULL,
    `width`  int,
    `height`  int,
    `attribution`    text,
    `created`  timestamp,
    `updated`  timestamp,
    PRIMARY KEY(`id`),
    INDEX (`plant_id`)
);
```

**Proposed** flow:
1. `/plants/:plant_id/images/new` shows `PlantImageUploadView` allows user to select an image to upload and enter attribution details (initialized with creative commons?)
2. User clicking _Upload_ sends image information and image to `POST /api/v0/plants/:plant_id/images/` which processes the image and places it in correct location, then redirects user to `/plants/:plant_id/images/:id/edit` on the resolution of a Deferred
3. `/plants/:plant_id/images/:id/edit` shows `PlantImageEditView` and allows user to crop the image
4. User clicking _Edit_ sends image cropping details to `PATCH /api/v0/plants/:plant_id/images/:id` which produces a modified copy, saves the result to the result to the correct location and redirects the user to `/plants/:plant_id/images/:id` on resolution of a Deferred
5. `/plants/:plant_id/images/:id` shows image and attribution

**Question - Scope**:  What's our scope?

**Decision - Scope**: We're going to ignore the crowd sourced aspect of images and just allow image uploading with out an account for now.  We'll add the authentication + crowd sourcing features in a later version after we add accounts in issue #41 and well before we release.

**Question - Attribution**: How are we going to handle attribution?
Options:
- Link to licenses / source
- Text field in which we can just put attribution details, then displayed on full image display page.

**Decision - Attribution**: We'll just handle attribution with a text field.

**Question - Editing**: What image editing features do we want to use?  What image editing library should we use?
Options:
- We have experience with [JCrop](http://deepliquid.com/content/Jcrop.html), which worked well for cropping. No development for 
- [CamanJS](https://github.com/meltingice/CamanJS) full featured image manipulation API with plugins, depends on converting the image to a canvas object.  No development for 3 years.
- [Darkroomjs](https://github.com/MattKetmo/darkroomjs) similar to CamanJS, less developed though. Very little development for 2 years.

**Decision - Editing**: I think we'll just use JCrop for now.  We can always upgrade to one of the more fully featured ones in the future, but for now we really just need cropping support and JCrop is the simplest and lightest weight provider of cropping.  I like DarkroomJS's extensibility, but it depends on a really heavy canvas library.  And CamanJS seems over complicated for our purposes (we don't need all those filters).

**Question - Storage**: How are we going to handle image storage?
Options:
- We could get a CDN.
- We could just store them on our server somewhere.

**Decision - Storage**: We're going to just store them on our server for now (keep things minimum viable).  We'll store them in `public/images` with two subdirectories, one for cropped images (`public/images/cropped`) and one for full images (`public/images/full`).  We'll store those paths in
configuration variables so we can change them easily.
for full images 

**Question - Local Development**: How are we going to handle images in local development?

**Decision - Local Development**: For now the same way as we do in production: we're just going to store them on the local server.  This means that if a developer destroys the vagrant it will lose its images.  That's fine for now.  We can come up with a better system (like syncing with production or referencing production) once we actually release.

**Comment by danielBingham** [comment]
**Decision - Migration** We're going to use a migration to create (update, actually) the images table.  I forgot an unused one existed in the schema from when it was first drafted.  But we should get in the habit of using migrations.

**Comment by danielBingham** [comment]
**Leftovers for Image Upload** 
- [ ] Need to write UI for upload page.  
- [ ] Upload page should redirect to image gallery page after upload is completed successfully.  
- [ ] Upload page shouldn't show the progress bar until the upload begins.  

**Question - Modal** Should we move the upload page into a modal on the gallery page?

**Question - Front End Organization** Front end kind of needs a reorganization refactor.  It's getting a little cluttered.  Subdirectories for models/views ?  Controllers under the router?
